In [7]:
import nltk
nltk.download('punkt')
nltk.download('stopwords')


[nltk_data] Error loading punkt: <urlopen error [SSL:
[nltk_data]     CERTIFICATE_VERIFY_FAILED] certificate verify failed:
[nltk_data]     unable to get local issuer certificate (_ssl.c:1000)>
[nltk_data] Error loading stopwords: <urlopen error [SSL:
[nltk_data]     CERTIFICATE_VERIFY_FAILED] certificate verify failed:
[nltk_data]     unable to get local issuer certificate (_ssl.c:1000)>


False

In [8]:
from sklearn.feature_extraction.text import TfidfVectorizer
from nltk import word_tokenize, bigrams
from nltk.corpus import stopwords


# Sample text corpus
corpus = [
    "I love programming in Python.",
    "Python is a great language for data science.",
    "Data science requires programming skills."
]

# Step 1: Tokenize and remove stopwords
stop_words = set(stopwords.words('english'))

def preprocess(text):
    tokens = word_tokenize(text.lower())  # Tokenize and lowercase
    tokens = [word for word in tokens if word.isalnum() and word not in stop_words]  # Remove stopwords and non-alphanumeric
    return tokens

# Step 2: Generate bigrams
def generate_bigrams(tokens):
    return [' '.join(bigram) for bigram in bigrams(tokens)]

# Preprocess the corpus and generate bigrams
bigram_corpus = [' '.join(generate_bigrams(preprocess(text))) for text in corpus]

# Step 3: Apply TF-IDF on bigrams
vectorizer = TfidfVectorizer()
tfidf_matrix = vectorizer.fit_transform(bigram_corpus)

# Display TF-IDF matrix
print("TF-IDF Matrix for Bigrams:")
print(tfidf_matrix.toarray())
print("Feature Names (Bigrams):", vectorizer.get_feature_names_out())

LookupError: 
**********************************************************************
  Resource stopwords not found.
  Please use the NLTK Downloader to obtain the resource:

  >>> import nltk
  >>> nltk.download('stopwords')
  
  For more information see: https://www.nltk.org/data.html

  Attempted to load corpora/stopwords

  Searched in:
    - '/Users/mithindev/nltk_data'
    - '/Users/mithindev/Desktop/COLLEGE/env/nltk_data'
    - '/Users/mithindev/Desktop/COLLEGE/env/share/nltk_data'
    - '/Users/mithindev/Desktop/COLLEGE/env/lib/nltk_data'
    - '/usr/share/nltk_data'
    - '/usr/local/share/nltk_data'
    - '/usr/lib/nltk_data'
    - '/usr/local/lib/nltk_data'
**********************************************************************


In [9]:
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer
import numpy as np

class TextRepresentation:
    def __init__(self, corpus):
        self.corpus = corpus
        self.vectorizer = None

    def one_hot_encode(self):
        # Create a vocabulary of unique words
        vocab = set()
        for text in self.corpus:
            vocab.update(text.split())
        vocab = sorted(vocab)  # Sort for consistent ordering

        # Generate one-hot encoding
        one_hot_vectors = []
        for text in self.corpus:
            vector = [1 if word in text.split() else 0 for word in vocab]
            one_hot_vectors.append(vector)
        return np.array(one_hot_vectors), vocab

    def bow(self):
        self.vectorizer = CountVectorizer()
        bow_matrix = self.vectorizer.fit_transform(self.corpus)
        return bow_matrix.toarray(), self.vectorizer.get_feature_names_out()

    def tfidf(self):
        self.vectorizer = TfidfVectorizer()
        tfidf_matrix = self.vectorizer.fit_transform(self.corpus)
        return tfidf_matrix.toarray(), self.vectorizer.get_feature_names_out()

# Example usage
corpus = [
    "I love programming in Python.",
    "Python is a great language for data science.",
    "Data science requires programming skills."
]

text_rep = TextRepresentation(corpus)

# One-Hot Encoding
one_hot, vocab = text_rep.one_hot_encode()
print("One-Hot Encoding:")
print(one_hot)
print("Vocabulary:", vocab)

# Bag of Words (BoW)
bow_matrix, bow_features = text_rep.bow()
print("\nBag of Words (BoW):")
print(bow_matrix)
print("BoW Features:", bow_features)

# TF-IDF
tfidf_matrix, tfidf_features = text_rep.tfidf()
print("\nTF-IDF:")
print(tfidf_matrix)
print("TF-IDF Features:", tfidf_features)

One-Hot Encoding:
[[0 1 0 1 0 0 0 0 1 0 0 1 1 0 0 0 0]
 [0 0 1 0 1 1 1 1 0 1 1 0 0 0 0 1 0]
 [1 0 0 0 0 0 0 0 0 0 0 0 1 1 1 0 1]]
Vocabulary: ['Data', 'I', 'Python', 'Python.', 'a', 'data', 'for', 'great', 'in', 'is', 'language', 'love', 'programming', 'requires', 'science', 'science.', 'skills.']

Bag of Words (BoW):
[[0 0 0 1 0 0 1 1 1 0 0 0]
 [1 1 1 0 1 1 0 0 1 0 1 0]
 [1 0 0 0 0 0 0 1 0 1 1 1]]
BoW Features: ['data' 'for' 'great' 'in' 'is' 'language' 'love' 'programming' 'python'
 'requires' 'science' 'skills']

TF-IDF:
[[0.         0.         0.         0.5628291  0.         0.
  0.5628291  0.42804604 0.42804604 0.         0.         0.        ]
 [0.31757018 0.41756662 0.41756662 0.         0.41756662 0.41756662
  0.         0.         0.31757018 0.         0.31757018 0.        ]
 [0.3935112  0.         0.         0.         0.         0.
  0.         0.3935112  0.         0.51741994 0.3935112  0.51741994]]
TF-IDF Features: ['data' 'for' 'great' 'in' 'is' 'language' 'love' 'progra